HIGH_RISK = {
    "registration fee": 40,
    "processing fee": 40,
    "telegram": 35,
    "whatsapp": 35,
    "crypto": 35,
    "bitcoin": 35,
    "upi": 25,
    "deposit": 30,
    "pay first": 40,
    "instant pay": 35,
    "guaranteed pay": 35,
    "guaranteed income": 35,
    "no interview": 30,
    "earn money": 25,
    "earn daily": 25,
    "work from home": 20,
    "part time": 20,
    "part-time": 20,
    "remote work": 20,
    "urgent hiring": 20,
    "limited seats": 20,
    "join immediately": 20,
}