import { jsPDF } from "jspdf";

export function downloadReport(result, analysisType) {

    const doc = new jsPDF();

    // ===== Header =====

    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 35, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("AI JobShield Pro", 20, 18);

    doc.setFontSize(12);
    doc.text("Recruitment Fraud Analysis Report", 20, 27);

    // ===== Reset Color =====

    doc.setTextColor(0, 0, 0);

    let y = 50;

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Analysis Summary", 20, y);

    y += 12;

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    doc.text(`Analysis Type : ${analysisType}`, 20, y);

    y += 10;

    doc.text(
        `Generated On : ${new Date().toLocaleString()}`,
        20,
        y
    );

    y += 15;

    // ===== Result Box =====

    doc.setFillColor(240, 248, 255);
    doc.roundedRect(18, y - 5, 170, 40, 3, 3, "F");

    doc.setFont("helvetica", "bold");

    doc.text(
        `Prediction : ${result.prediction}`,
        25,
        y + 5
    );

    doc.text(
        `Fraud Score : ${result.fraud_score}`,
        25,
        y + 15
    );

    doc.text(
        `Confidence : ${result.confidence}%`,
        25,
        y + 25
    );

    y += 55;

    // ===== Keywords =====

    doc.setFontSize(15);
    doc.text("Detected Scam Indicators", 20, y);

    y += 10;

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    if (
        result.keywords_found &&
        result.keywords_found.length > 0
    ) {

        result.keywords_found.forEach((item) => {

            doc.text("• " + item, 25, y);

            y += 8;

        });

    } else {

        doc.text(
            "No suspicious keywords detected.",
            25,
            y
        );

        y += 8;

    }

    y += 10;

    // ===== Recommendation =====

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);

    doc.text("Recommendation", 20, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    let recommendation = "";

    if (result.prediction === "Highly Suspicious") {

        recommendation =
            "Avoid applying for this job. Multiple fraud indicators were detected.";

    } else if (result.prediction === "Suspicious") {

        recommendation =
            "Proceed carefully. Verify the employer before sharing personal information.";

    } else {

        recommendation =
            "No major fraud indicators were detected. Continue with normal verification.";

    }

    const lines = doc.splitTextToSize(
        recommendation,
        170
    );

    doc.text(lines, 20, y);

    y += 25;

    // ===== Footer =====

    doc.setDrawColor(180);
    doc.line(20, 270, 190, 270);

    doc.setFontSize(10);

    doc.text(
        "Generated by AI JobShield Pro",
        20,
        280
    );

    doc.text(
        "Developed by S Hemanth Naidu",
        20,
        286
    );

    doc.save("AI_JobShield_Report.pdf");
}